[package]
name = "xsd-types"
version = "0.0.1"
description = "Structure generator from XSD source file"
edition = "2021"

[lib]
name = "xsd_types"

[dependencies]
heck = "0.3.1"
xmltree = "0.10.3"
thiserror = "1.0.30"

[dev-dependencies]
